language: c
env:
  global:
    #- GIT_URL=https://github.com/skotchpine/asdf-maven.git
    - GIT_URL=https://github.com/spencerdcarlson/asdf-maven.git
script: 
    - echo "Begin asdf-maven plugin test"
    - asdf plugin-test maven ${GIT_URL}
    - unset JAVA_HOME
    - asdf plugin-list
    - echo "Add asdf-java plugin"
    - echo "Install the latest java version"
    # asdf install java is failing on macOS for some reason
    - asdf install java $(asdf list-all java | tail -n 1)
    - echo "Set local asdf java version"
    - asdf local java $(asdf list-all java | tail -n 1)
    - echo "java version set to $(asdf list-all java | tail -n 1)"  
    - echo "Installing asdf-maven plugin"
    - asdf plugin-add maven $TRAVIS_BUILD_DIR
    - echo "List all versions of maven"
    - asdf list-all maven
    - echo "install the latest maven version"
    - asdf install maven $(asdf list-all maven | tail -n 1)
    - echo "set local asdf maven version"
    - asdf local maven $(asdf list-all maven | tail -n 1)
    - echo "set the local maven version $(asdf list-all maven | tail -n 1)"  
    - echo "test mvn command"
    - echo -e "echo JAVACMD=\$JAVA_HOME/bin/java\n$(cat ${HOME}/.asdf/installs/maven/3.6.1/bin/mvn)" > ${HOME}/.asdf/installs/maven/3.6.1/bin/mvn
    - echo "execute java -version"
    - asdf plugin-list
    - ls ${HOME}/.asdf/installs 
    - ls ${HOME}/.asdf/installs/java
    - ls ${HOME}/.asdf/installs/java/zulu-12.0.1
    - ls ${HOME}/.asdf/installs/java/zulu-12.0.1/bin
    - ${HOME}/.asdf/installs/java/zulu-12.0.1/bin/java -version
    - mvn -version 2>&1
    - mvn -version 2>&1 | grep $(asdf list-all maven | tail -n 1)
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
