language: c
env:
  global:
    - ASDF_MAVEN_URL=https://github.com/spencerdcarlson/asdf-maven.git
    - ASDF_JAVA_URL=https://github.com/rud/asdf-java.git
    # - ASDF_JAVA_URL=https://github.com/skotchpine/asdf-java.git
    # - ASDF_MAVEN_URL=https://github.com/skotchpine/asdf-maven.git
script:
    - echo "begin asdf-maven plugin test"
    - asdf plugin-test maven ${ASDF_MAVEN_URL}
    - unset JAVA_HOME
    - asdf plugin-add java ${ASDF_JAVA_URL} && echo "added asdf-java plugin (${ASDF_JAVA_URL})"
    - asdf install java $(asdf list-all java | tail -n 1) && echo "installed java ($(asdf list-all java | tail -n 1))"
    - asdf local java $(asdf list-all java | tail -n 1)
    - asdf plugin-add maven $TRAVIS_BUILD_DIR && echo "added asdf-maven plugin"  
    - asdf install maven $(asdf list-all maven | tail -n 1) && echo "installed maven ($(asdf list-all maven | tail -n 1))"
    - asdf local maven $(asdf list-all maven | tail -n 1)
    - mvn -version 2>&1 | grep $(asdf list-all maven | tail -n 1) && echo "mvn test was successful"
before_script:
  - git clone -q https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
